# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_footersettings_socialsharingseosettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='attribution',
            field=models.CharField(blank=True, help_text='Organization/Photographer.', max_length=255, null=True),
        ),
    ]
